### ISSUE TITLE
Reduction of computational requirements for generating C4_200M

### ISSUE THREAD

**Issue by palasso** [google-research-datasets/C4_200M-synthetic-dataset-for-grammatical-error-correction#2]
Obtaining and generating the clean version of the C4 corpus version 2.2.1 seems to be computationally expensive.

Are there any plans for an alternative way to generate the C4_200M dataset?

For example, obtaining the C4 clean version 3.0.1 seems more easy as it is available by [allennlp](https://github.com/allenai/allennlp/discussions/5056), or, alternatively, providing a downloadable C4 clean version 2.2.1 would also make it easier.

Thank you 🙂

**Comment by fstahlberg** [comment]
Hi,

we cannot provide a downloadable C4 2.2.1 version, but you can try to simply use v3.0.1 instead - I could imagine that the difference between versions is small enough to get away with loosing no more than a small fraction of the sentences, especially since we're only using a 200M subset. If you do try, please let us know here.

Best, Felix

**Comment by palasso** [comment]
Hi,

I tried with C4 v3.0.1 resulting into 183894319 sentence pairs.

Kind regards,
Vassilis

**Comment by fstahlberg** [comment]
Thanks so much for checking, I've added a note to the readme.

**Comment by PrithivirajDamodaran** [comment]
Yes, I can confirm using v3.0.1 works fine,

**Comment by Giovanni-Alzetta** [comment]
I guess this is how the other people here did it, but I can confirm v3.0.1 works and the script for data generation `c4200m_get_target_sentences.py` requires few changes if you want to use the json files directly (allenai provides only those for free).

If @fstahlberg deems it useful I can provide the modified script, but it almost feels like overkill (the only change is to change the for loop to read a json file...).

**Comment by fstahlberg** [comment]
@Giovanni-Alzetta An additional `get_target_sentences` script that grabs the sentences from allenai is definitely useful. It would be great if you could make a PR - thanks!

**Comment by ZhouJunyu9102** [comment]
183894801/2000000 sentences

**Comment by 5hogun-Ormerod** [comment]
I would also like to know what the changes to the loop are in order to get the target sentences. Either @Giovanni-Alzetta , @PrithivirajDamodaran, @palasso please post changes to the get_target_sentences.py to get the required 183894319 sentence pairs. I would love to use the dataset myself.

**Comment by palasso** [comment]
I downloaded the TFDS version from allennlp (which costs about $100):
```
mkdir -p local_datasets_dir/c4/en/3.0.1/
gsutil -u <google-cloud-project-name> -m cp 'gs://allennlp-tensorflow-datasets/c4/en/3.0.1/*' local_datasets_dir/c4/en/3.0.1/
```
and modified line 28 of `c4200m_get_target_sentences.py` accordingly:
```
tfds.load("c4/en", download=False, data_dir="local_datasets_dir/c4/en/3.0.1/", split="train")
```

**Comment by Giovanni-Alzetta** [comment]
Sorry for the delay, here is the script:
https://github.com/google-research-datasets/C4_200M-synthetic-dataset-for-grammatical-error-correction/pull/3
I actually changed some stuff so I'm running it again on an edit file just for a final check, but it should be fine.

**Comment by ayaka14732** [comment]
@palasso

> I downloaded the TFDS version from allennlp (which costs about $100):
> 
> ```
> mkdir -p local_datasets_dir/c4/en/3.0.1/
> gsutil -u <google-cloud-project-name> -m cp 'gs://allennlp-tensorflow-datasets/c4/en/3.0.1/*' local_datasets_dir/c4/en/3.0.1/
> ```
> 
> and modified line 28 of `c4200m_get_target_sentences.py` accordingly:
> 
> ```
> tfds.load("c4/en", download=False, data_dir="local_datasets_dir/c4/en/3.0.1/", split="train")
> ```

The last line should be:

```
tfds.load("c4/en", download=False, data_dir="local_datasets_dir/", split="train")
```
