### ISSUE TITLE
Synthetical datasets for other languages (e.g German, Spanish, French)

### ISSUE THREAD

**Issue by BogdanDidenko** [google-research-datasets/C4_200M-synthetic-dataset-for-grammatical-error-correction#6]
Do you have plans to create synthetical datasets based on Tagged Corruption Models for other languages? 
For example, for the German language. The [Falco+MERLIN corpus](https://aclanthology.org/W18-6111.pdf) and [Gernam Errant fork](https://github.com/adrianeboyd/errant/tree/german)  would be helpful to create a desired tag distribution.
Or for Spanish based on [COWS-L2H Corpus](https://aclanthology.org/2020.lrec-1.894.pdf).

It would be very useful to have similar synthetic data for several popular languages.

**Comment by fstahlberg** [comment]
I agree that this would be a natural and useful extension of this work - especially for German using the German ERRANT version you are referring to. However, it doesn't match our current priorities and we are not actively working on that - maybe we find time in 2022 :)
