### ISSUE TITLE
Dataset used to train the corruption model

### ISSUE THREAD

**Issue by GokulNC** [google-research-datasets/C4_200M-synthetic-dataset-for-grammatical-error-correction#7]
Hi @fstahlberg 

Is there any plan to release the following tag-annotated dataset(s)?

_From [Section 2](https://aclanthology.org/2021.bea-1.4.pdf):_
> A straightforward way to train such a tagged corruption model is to annotate a parallel corpus with ERRANT...

**Comment by fstahlberg** [comment]
Hi,

we are unable to release the tag-annotated datasets because we don't own the original data. However, ERRANT is pretty fast and can annotate sizable datasets in a manageable amount of time even on local CPUs.

Best, Felix
