### ISSUE TITLE
Any plan to release extra code?

### ISSUE THREAD

**Issue by lxsyz** [google-research-datasets/C4_200M-synthetic-dataset-for-grammatical-error-correction#8]
Hi @fstahlberg

Is there any plan to release related code about beam search and constraining FSTs?

Thank you!

**Comment by fstahlberg** [comment]
Hi,

We are not planing to release the code, but our implementation is very similar to the [open-source SGNMT toolkit](https://ucam-smt.github.io/sgnmt/html/index.html).

Best, Felix
