### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by saramoeini20** [google-research-datasets/C4_200M-synthetic-dataset-for-grammatical-error-correction#9]
Hi, 
I want to know if i understood right
Did you used the dataset (C4 corpus) and then tagged it with ERRANT to then use that edits for creating parallel data?
If yes then i should say if i want to produce the first dataset (I mean something like C4 corpus) myself what methods exist?

**Comment by fstahlberg** [comment]
Hi,

the C4 dataset is available on tf Datasets (https://www.tensorflow.org/datasets/catalog/c4) but it needs manual downloads. Have a look at c4200m_get_target_sentences.py to see how to read from tf.Datasets in Python. Alternatively, you can also get the c4 dataset from Huggingface.

Best,
Felix

**Comment by saramoeini20** [comment]
Actually i want to do it for another language so can't use it. Wanted to know if it is possible to produce something like C4 dataset myself

**Comment by fstahlberg** [comment]
There's multilingual C4 (https://huggingface.co/datasets/mc4), but if it doesn't cover your language you probably need to crawl data yourself..

**Comment by saramoeini20** [comment]
thank you
